name: Sync labels

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: 🏷️ Sync labels
        uses: EndBug/label-sync@7753e99e1e64188c24d7deede343c5a63e7c0d39 # v2.3.3
        with:
          config-file: https://raw.githubusercontent.com/VanOns/open-source-template/main/template/.github/labels.yml
          request-token: ${{ secrets.LABEL_SYNC_TOKEN }}
