name: Update changelog

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.release.target_commitish }}
          persist-credentials: false

      - name: Update changelog
        uses: stefanzweifel/changelog-updater-action@a938690fad7edf25368f37e43a1ed1b34303eb36 # v1.12.0
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: chore/update-changelog-${{ github.event.release.tag_name }}
          commit-message: "chore: update CHANGELOG.md"
          title: "chore: update CHANGELOG.md for ${{ github.event.release.tag_name }}"
          body: "Automated changelog update for release ${{ github.event.release.tag_name }}"
          labels: documentation
          delete-branch: true
