name: Update changelog

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Update changelog
        uses: stefanzweifel/changelog-updater-action@a938690fad7edf25368f37e43a1ed1b34303eb36 # v1.12.0
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          branch: chore/update-changelog-${{ github.event.release.tag_name }}
          commit-message: "chore: update CHANGELOG.md"
          title: "chore: update CHANGELOG.md for ${{ github.event.release.tag_name }}"
          body: "Automated changelog update for release ${{ github.event.release.tag_name }}"
          labels: documentation
          delete-branch: true
